# generated by h2ctypes, do not touch

from ctypes import *
from procwrap import *

# predefines
size_t = c_ulong
_IO_FILE = c_ulong
__ssize_t = c_int
ssize_t = c_uint

# defines
# ZZUB_CALLING_CONVENTION = __attribute__((cdecl))
# ZZUB_EXTERN_C = extern "C"

# using file "/root/src/zzub/include/zzub/types.h"
# using file "src/libzzub/libzzub.h"
class _zzub_plugin(Structure):
	_fields_ = [
	]

zzub_plugin_t = _zzub_plugin

class zzub_event_data_new_plugin(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
	]

zzub_event_data_new_plugin_t = zzub_event_data_new_plugin

class zzub_event_data_delete_plugin(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
	]

zzub_event_data_delete_plugin_t = zzub_event_data_delete_plugin

class zzub_event_data_midi_message(Structure):
	_fields_ = [
		('status', c_ubyte),
		('data1', c_ubyte),
		('data2', c_ubyte),
	]

zzub_event_data_midi_message_t = zzub_event_data_midi_message

class zzub_event_data_connect(Structure):
	_fields_ = [
		('from_plugin', POINTER(zzub_plugin_t)),
		('to_plugin', POINTER(zzub_plugin_t)),
		('type', c_int),
	]

zzub_event_data_connect_t = zzub_event_data_connect

class zzub_event_data_plugin_changed(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
	]

zzub_event_data_plugin_changed_t = zzub_event_data_plugin_changed

class zzub_event_data_change_parameter(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
		('group', c_int),
		('track', c_int),
		('param', c_int),
		('value', c_int),
	]

zzub_event_data_change_parameter_t = zzub_event_data_change_parameter

class zzub_event_data_set_tracks(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
	]

zzub_event_data_set_tracks_t = zzub_event_data_set_tracks

class zzub_event_data_player_state_changed(Structure):
	_fields_ = [
		('player_state', c_int),
	]

zzub_event_data_player_state_changed_t = zzub_event_data_player_state_changed

class zzub_event_data_osc_message(Structure):
	_fields_ = [
		('path', c_char_p),
		('types', c_char_p),
		('argv', POINTER(c_void_p)),
		('argc', c_int),
		('msg', c_void_p),
	]

zzub_event_data_osc_message_t = zzub_event_data_osc_message

class zzub_event_data_vu(Structure):
	_fields_ = [
		('size', c_int),
		('left_amp', c_float),
		('right_amp', c_float),
		('time', c_float),
	]

zzub_event_data_vu_t = zzub_event_data_vu

class _zzub_archive(Structure):
	_fields_ = [
	]

zzub_archive_t = _zzub_archive

class zzub_event_data_serialize(Structure):
	_fields_ = [
		('mode', c_char),
		('archive', POINTER(zzub_archive_t)),
	]

zzub_event_data_serialize_t = zzub_event_data_serialize

class zzub_event_data_set_sequence_tracks(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
	]

zzub_event_data_set_sequence_tracks_t = zzub_event_data_set_sequence_tracks

class zzub_event_data_set_sequence_event(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
		('track', c_int),
		('time', c_int),
	]

zzub_event_data_set_sequence_event_t = zzub_event_data_set_sequence_event

class zzub_event_data_new_pattern(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
		('index', c_int),
	]

zzub_event_data_new_pattern_t = zzub_event_data_new_pattern

class zzub_event_data_delete_pattern(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
		('index', c_int),
	]

zzub_event_data_delete_pattern_t = zzub_event_data_delete_pattern

class zzub_event_data_edit_pattern(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
		('index', c_int),
		('group', c_int),
		('track', c_int),
		('column', c_int),
		('row', c_int),
		('value', c_int),
	]

zzub_event_data_edit_pattern_t = zzub_event_data_edit_pattern

class zzub_event_data_pattern_changed(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
		('index', c_int),
	]

zzub_event_data_pattern_changed_t = zzub_event_data_pattern_changed

class zzub_event_data_change_wave(Structure):
	_fields_ = [
		('wave', c_int),
		('level', c_int),
	]

zzub_event_data_change_wave_t = zzub_event_data_change_wave

class zzub_event_data_delete_wave(Structure):
	_fields_ = [
		('wave', c_int),
		('level', c_int),
	]

zzub_event_data_delete_wave_t = zzub_event_data_delete_wave

class zzub_event_data_allocate_wave(Structure):
	_fields_ = [
		('wave', c_int),
		('level', c_int),
	]

zzub_event_data_allocate_wave_t = zzub_event_data_allocate_wave

class zzub_event_data_pattern_insert_rows(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
		('index', c_int),
		('row', c_int),
		('rows', c_int),
		('column_indices', POINTER(c_int)),
		('indices', c_int),
	]

zzub_event_data_pattern_insert_rows_t = zzub_event_data_pattern_insert_rows

class zzub_event_data_pattern_remove_rows(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
		('index', c_int),
		('row', c_int),
		('rows', c_int),
		('column_indices', POINTER(c_int)),
		('indices', c_int),
	]

zzub_event_data_pattern_remove_rows_t = zzub_event_data_pattern_remove_rows

class zzub_event_data_custom(Structure):
	_fields_ = [
		('id', c_int),
		('data', c_void_p),
	]

zzub_event_data_custom_t = zzub_event_data_custom

zzub_event_data_all_t = 'zzub_event_data_all'

class zzub_event_data_unknown(Structure):
	_fields_ = [
		('param', c_void_p),
	]

zzub_event_data_unknown_t = zzub_event_data_unknown

class union__71d665b6(Union):
	_fields_ = [
		('new_plugin', zzub_event_data_new_plugin_t),
		('delete_plugin', zzub_event_data_delete_plugin_t),
		('midi_message', zzub_event_data_midi_message_t),
		('connect_plugin', zzub_event_data_connect_t),
		('disconnect_plugin', zzub_event_data_connect_t),
		('plugin_changed', zzub_event_data_plugin_changed_t),
		('change_parameter', zzub_event_data_change_parameter_t),
		('set_tracks', zzub_event_data_set_tracks_t),
		('player_state_changed', zzub_event_data_player_state_changed_t),
		('osc_message', zzub_event_data_osc_message_t),
		('vu', zzub_event_data_vu_t),
		('serialize', zzub_event_data_serialize_t),
		('set_sequence_tracks', zzub_event_data_set_sequence_tracks_t),
		('set_sequence_event', zzub_event_data_set_sequence_event_t),
		('new_pattern', zzub_event_data_new_pattern_t),
		('delete_pattern', zzub_event_data_delete_pattern_t),
		('edit_pattern', zzub_event_data_edit_pattern_t),
		('pattern_changed', zzub_event_data_pattern_changed_t),
		('change_wave', zzub_event_data_change_wave_t),
		('delete_wave', zzub_event_data_delete_wave_t),
		('allocate_wave', zzub_event_data_allocate_wave_t),
		('pattern_insert_rows', zzub_event_data_pattern_insert_rows_t),
		('pattern_remove_rows', zzub_event_data_pattern_remove_rows_t),
		('custom', zzub_event_data_custom_t),
		('all', zzub_event_data_all_t),
		('unknown', zzub_event_data_unknown_t),
	]

class zzub_event_data(Structure):
	_fields_ = [
		('type', c_int),
		('', union__71d665b6),
	]

zzub_event_data_t = zzub_event_data

class zzub_event_data_all(Structure):
	_fields_ = [
		('data', POINTER(zzub_event_data_t)),
	]

class _zzub_attribute(Structure):
	_fields_ = [
	]

zzub_attribute_t = _zzub_attribute

class _zzub_parameter(Structure):
	_fields_ = [
	]

zzub_parameter_t = _zzub_parameter

class _zzub_player(Structure):
	_fields_ = [
	]

zzub_player_t = _zzub_player

