# generated by h2ctypes, do not touch

from ctypes import *
from procwrap import *

# predefines
size_t = c_ulong
_IO_FILE = c_ulong
__ssize_t = c_int
ssize_t = c_uint

# defines
# ZZUB_CALLING_CONVENTION = __attribute__((cdecl))
# ZZUB_EXTERN_C = extern "C"

# using file "/home/paniq/devel/zzub/include/zzub/types.h"
# using file "src/libzzub/libzzub.h"
class _zzub_attribute(Structure):
	_fields_ = [
	]

zzub_attribute_t = _zzub_attribute

class _zzub_parameter(Structure):
	_fields_ = [
	]

zzub_parameter_t = _zzub_parameter

class _zzub_player(Structure):
	_fields_ = [
	]

zzub_player_t = _zzub_player

class _zzub_plugin(Structure):
	_fields_ = [
	]

zzub_plugin_t = _zzub_plugin

class zzub_event_data_new_plugin(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
	]

zzub_event_data_new_plugin_t = zzub_event_data_new_plugin

class zzub_event_data_delete_plugin(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
	]

zzub_event_data_delete_plugin_t = zzub_event_data_delete_plugin

class zzub_event_data_midi_message(Structure):
	_fields_ = [
		('status', c_ubyte),
		('data1', c_ubyte),
		('data2', c_ubyte),
	]

zzub_event_data_midi_message_t = zzub_event_data_midi_message

class _zzub_connection(Structure):
	_fields_ = [
	]

zzub_connection_t = _zzub_connection

class zzub_event_data_connect(Structure):
	_fields_ = [
		('connection', POINTER(zzub_connection_t)),
	]

zzub_event_data_connect_t = zzub_event_data_connect

class zzub_event_data_change_parameter(Structure):
	_fields_ = [
		('group', c_uint),
		('track', c_uint),
		('param', c_uint),
		('value', c_uint),
	]

zzub_event_data_change_parameter_t = zzub_event_data_change_parameter

class zzub_event_data_set_tracks(Structure):
	_fields_ = [
		('plugin', POINTER(zzub_plugin_t)),
	]

zzub_event_data_set_tracks_t = zzub_event_data_set_tracks

class zzub_event_data_player_state_changed(Structure):
	_fields_ = [
		('player_state', c_int),
	]

zzub_event_data_player_state_changed_t = zzub_event_data_player_state_changed

class zzub_event_data_osc_message(Structure):
	_fields_ = [
		('path', c_char_p),
		('types', c_char_p),
		('argv', POINTER(c_void_p)),
		('argc', c_int),
		('msg', c_void_p),
	]

zzub_event_data_osc_message_t = zzub_event_data_osc_message

class zzub_event_data_vu(Structure):
	_fields_ = [
		('size', c_int),
		('left_amp', c_float),
		('right_amp', c_float),
		('time', c_float),
	]

zzub_event_data_vu_t = zzub_event_data_vu

class _zzub_archive(Structure):
	_fields_ = [
	]

zzub_archive_t = _zzub_archive

class zzub_event_data_serialize(Structure):
	_fields_ = [
		('mode', c_char),
		('archive', POINTER(zzub_archive_t)),
	]

zzub_event_data_serialize_t = zzub_event_data_serialize

zzub_event_data_t = 'zzub_event_data'

class zzub_event_data_all(Structure):
	_fields_ = [
		('data', POINTER(zzub_event_data_t)),
	]

zzub_event_data_all_t = zzub_event_data_all

class zzub_event_data_unknown(Structure):
	_fields_ = [
		('param', c_void_p),
	]

zzub_event_data_unknown_t = zzub_event_data_unknown

class union__b5b0fe8b(Union):
	_fields_ = [
		('new_plugin', zzub_event_data_new_plugin_t),
		('delete_plugin', zzub_event_data_delete_plugin_t),
		('midi_message', zzub_event_data_midi_message_t),
		('connect_plugin', zzub_event_data_connect_t),
		('disconnect_plugin', zzub_event_data_connect_t),
		('change_parameter', zzub_event_data_change_parameter_t),
		('set_tracks', zzub_event_data_set_tracks_t),
		('player_state_changed', zzub_event_data_player_state_changed_t),
		('osc_message', zzub_event_data_osc_message_t),
		('vu', zzub_event_data_vu_t),
		('serialize', zzub_event_data_serialize_t),
		('pre_connect_plugin', zzub_event_data_connect_t),
		('pre_disconnect_plugin', zzub_event_data_connect_t),
		('pre_set_tracks', zzub_event_data_set_tracks_t),
		('all', zzub_event_data_all_t),
		('unknown', zzub_event_data_unknown_t),
	]

class zzub_event_data(Structure):
	_fields_ = [
		('type', c_int),
		('', union__b5b0fe8b),
	]

zzub_event_data_t = zzub_event_data

class _zzub_plugincollection(Structure):
	_fields_ = [
	]

zzub_plugincollection_t = _zzub_plugincollection

class _zzub_midimapping(Structure):
	_fields_ = [
	]

zzub_midimapping_t = _zzub_midimapping

class _zzub_input(Structure):
	_fields_ = [
	]

zzub_input_t = _zzub_input

class _zzub_pluginloader(Structure):
	_fields_ = [
	]

zzub_pluginloader_t = _zzub_pluginloader

class _zzub_postprocess(Structure):
	_fields_ = [
	]

zzub_postprocess_t = _zzub_postprocess

class _zzub_audio_connection(Structure):
	_fields_ = [
	]

zzub_audio_connection_t = _zzub_audio_connection

class _zzub_event_connection(Structure):
	_fields_ = [
	]

zzub_event_connection_t = _zzub_event_connection

class _zzub_event_connection_binding(Structure):
	_fields_ = [
	]

zzub_event_connection_binding_t = _zzub_event_connection_binding

class _zzub_sequencer(Structure):
	_fields_ = [
	]

zzub_sequencer_t = _zzub_sequencer

class _zzub_sequence(Structure):
	_fields_ = [
	]

zzub_sequence_t = _zzub_sequence

class _zzub_patterntrack(Structure):
	_fields_ = [
	]

zzub_patterntrack_t = _zzub_patterntrack

class _zzub_pattern(Structure):
	_fields_ = [
	]

zzub_pattern_t = _zzub_pattern

class _zzub_wave(Structure):
	_fields_ = [
	]

zzub_wave_t = _zzub_wave

class _zzub_wavelevel(Structure):
	_fields_ = [
	]

zzub_wavelevel_t = _zzub_wavelevel

class _zzub_envelope(Structure):
	_fields_ = [
	]

zzub_envelope_t = _zzub_envelope

zzub_event_id = c_void_p

# enumeration ._0
zzub_version = 15
zzub_buffer_size = 256

# enumeration zzub_event_type
zzub_event_type_double_click = 0
zzub_event_type_new_plugin = 1
zzub_event_type_delete_plugin = 2
zzub_event_type_disconnect = 3
zzub_event_type_connect = 4
zzub_event_type_parameter_changed = 7
zzub_event_type_set_tracks = 13
zzub_event_type_pre_disconnect = 14
zzub_event_type_pre_connect = 15
zzub_event_type_pre_set_tracks = 16
zzub_event_type_load_progress = 8
zzub_event_type_midi_control = 11
zzub_event_type_wave_allocated = 12
zzub_event_type_player_state_changed = 20
zzub_event_type_osc_message = 21
zzub_event_type_vu = 22
zzub_event_type_all = 255

# enumeration zzub_player_state
zzub_player_state_playing = 0
zzub_player_state_stopped = 1
zzub_player_state_muted = 2
zzub_player_state_released = 3

class _zzub_output(Structure):
	_fields_ = [
	]

zzub_output_t = _zzub_output

ZzubCallback = CFUNCTYPE(c_int,POINTER(zzub_player_t),POINTER(zzub_plugin_t),POINTER(zzub_event_data_t),c_void_p)

ZzubMixCallback = CFUNCTYPE(None,POINTER(c_float),POINTER(c_float),c_int,c_void_p)

# enumeration zzub_parameter_type
zzub_parameter_type_note = 0
zzub_parameter_type_switch = 1
zzub_parameter_type_byte = 2
zzub_parameter_type_word = 3

# enumeration zzub_wave_buffer_type
zzub_wave_buffer_type_si16 = 0
zzub_wave_buffer_type_f32 = 1
zzub_wave_buffer_type_si32 = 2
zzub_wave_buffer_type_si24 = 3

# enumeration zzub_oscillator_type
zzub_oscillator_type_sine = 0
zzub_oscillator_type_sawtooth = 1
zzub_oscillator_type_pulse = 2
zzub_oscillator_type_triangle = 3
zzub_oscillator_type_noise = 4
zzub_oscillator_type_sawtooth_303 = 5

# enumeration zzub_note_value
zzub_note_value_none = 0
zzub_note_value_off = 255
zzub_note_value_min = 1
zzub_note_value_max = 156
zzub_note_value_c4 = 65

# enumeration zzub_switch_value
zzub_switch_value_none = 255
zzub_switch_value_off = 0
zzub_switch_value_on = 1

# enumeration zzub_wavetable_index_value
zzub_wavetable_index_value_none = 0
zzub_wavetable_index_value_min = 1
zzub_wavetable_index_value_max = 200

# enumeration zzub_parameter_flag
zzub_parameter_flag_wavetable_index = 1
zzub_parameter_flag_state = 2
zzub_parameter_flag_event_on_edit = 4

# enumeration zzub_plugin_flag
zzub_plugin_flag_mono_to_stereo = 1
zzub_plugin_flag_plays_waves = 2
zzub_plugin_flag_uses_lib_interface = 4
zzub_plugin_flag_uses_instruments = 8
zzub_plugin_flag_does_input_mixing = 16
zzub_plugin_flag_control_plugin = 64
zzub_plugin_flag_auxiliary = 128
zzub_plugin_flag_is_root = 65536
zzub_plugin_flag_has_audio_input = 131072
zzub_plugin_flag_has_audio_output = 262144
zzub_plugin_flag_has_event_input = 524288
zzub_plugin_flag_has_event_output = 1048576

# enumeration zzub_state_flag
zzub_state_flag_playing = 1
zzub_state_flag_recording = 2

# enumeration zzub_wave_flag
zzub_wave_flag_loop = 1
zzub_wave_flag_extended = 4
zzub_wave_flag_stereo = 8
zzub_wave_flag_pingpong = 16
zzub_wave_flag_envelope = 128

# enumeration zzub_envelope_flag
zzub_envelope_flag_sustain = 1
zzub_envelope_flag_loop = 2

# enumeration zzub_process_mode
zzub_process_mode_no_io = 0
zzub_process_mode_read = 1
zzub_process_mode_write = 2
zzub_process_mode_read_write = 3

# enumeration zzub_connection_type
zzub_connection_type_audio = 0
zzub_connection_type_event = 1

libzzub = dlopen('zzub',version='0.2.4')
zzub_audiodriver_get_count               = dlsym(libzzub, 'zzub_audiodriver_get_count'            , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_audiodriver_get_name                = dlsym(libzzub, 'zzub_audiodriver_get_name'             , c_int, ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ),('name'    ,c_char_p  ),('maxLen'  ,c_int     ))
zzub_audiodriver_create                  = dlsym(libzzub, 'zzub_audiodriver_create'               , c_int, ('player'  ,POINTER(zzub_player_t)),('input_index',c_int     ),('output_index',c_int     ))
zzub_audiodriver_enable                  = dlsym(libzzub, 'zzub_audiodriver_enable'               , None, ('player'  ,POINTER(zzub_player_t)),('state'   ,c_int     ))
zzub_audiodriver_destroy                 = dlsym(libzzub, 'zzub_audiodriver_destroy'              , None, ('player'  ,POINTER(zzub_player_t)))
zzub_audiodriver_set_samplerate          = dlsym(libzzub, 'zzub_audiodriver_set_samplerate'       , None, ('player'  ,POINTER(zzub_player_t)),('samplerate',c_uint    ))
zzub_audiodriver_get_samplerate          = dlsym(libzzub, 'zzub_audiodriver_get_samplerate'       , c_uint, ('player'  ,POINTER(zzub_player_t)))
zzub_audiodriver_set_buffersize          = dlsym(libzzub, 'zzub_audiodriver_set_buffersize'       , None, ('player'  ,POINTER(zzub_player_t)),('buffersize',c_uint    ))
zzub_audiodriver_get_buffersize          = dlsym(libzzub, 'zzub_audiodriver_get_buffersize'       , c_uint, ('player'  ,POINTER(zzub_player_t)))
zzub_audiodriver_get_cpu_load            = dlsym(libzzub, 'zzub_audiodriver_get_cpu_load'         , c_double, ('player'  ,POINTER(zzub_player_t)))
zzub_audiodriver_is_output               = dlsym(libzzub, 'zzub_audiodriver_is_output'            , c_int, ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ))
zzub_audiodriver_is_input                = dlsym(libzzub, 'zzub_audiodriver_is_input'             , c_int, ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ))
zzub_mididriver_get_count                = dlsym(libzzub, 'zzub_mididriver_get_count'             , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_mididriver_get_name                 = dlsym(libzzub, 'zzub_mididriver_get_name'              , c_char_p, ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ))
zzub_mididriver_is_input                 = dlsym(libzzub, 'zzub_mididriver_is_input'              , c_int, ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ))
zzub_mididriver_is_output                = dlsym(libzzub, 'zzub_mididriver_is_output'             , c_int, ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ))
zzub_mididriver_open                     = dlsym(libzzub, 'zzub_mididriver_open'                  , c_int, ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ))
zzub_mididriver_close_all                = dlsym(libzzub, 'zzub_mididriver_close_all'             , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_plugincollection_by_uri  = dlsym(libzzub, 'zzub_player_get_plugincollection_by_uri', POINTER(zzub_plugincollection_t), ('player'  ,POINTER(zzub_player_t)),('uri'     ,c_char_p  ))
zzub_plugincollection_configure          = dlsym(libzzub, 'zzub_plugincollection_configure'       , None, ('collection',POINTER(zzub_plugincollection_t)),('key'     ,c_char_p  ),('value'   ,c_char_p  ))
zzub_player_create                       = dlsym(libzzub, 'zzub_player_create'                    , POINTER(zzub_player_t), )
zzub_player_destroy                      = dlsym(libzzub, 'zzub_player_destroy'                   , None, ('player'  ,POINTER(zzub_player_t)))
zzub_player_add_plugin_path              = dlsym(libzzub, 'zzub_player_add_plugin_path'           , None, ('player'  ,POINTER(zzub_player_t)),('path'    ,c_char_p  ))
zzub_player_blacklist_plugin             = dlsym(libzzub, 'zzub_player_blacklist_plugin'          , None, ('player'  ,POINTER(zzub_player_t)),('uri'     ,c_char_p  ))
zzub_player_add_plugin_alias             = dlsym(libzzub, 'zzub_player_add_plugin_alias'          , None, ('player'  ,POINTER(zzub_player_t)),('name'    ,c_char_p  ),('uri'     ,c_char_p  ))
zzub_player_initialize                   = dlsym(libzzub, 'zzub_player_initialize'                , c_int, ('player'  ,POINTER(zzub_player_t)),('samplesPerSecond',c_int     ))
zzub_player_load_bmx                     = dlsym(libzzub, 'zzub_player_load_bmx'                  , c_int, ('player'  ,POINTER(zzub_player_t)),('fileName',c_char_p  ))
zzub_player_save_bmx                     = dlsym(libzzub, 'zzub_player_save_bmx'                  , c_int, ('player'  ,POINTER(zzub_player_t)),('fileName',c_char_p  ))
zzub_player_load_ccm                     = dlsym(libzzub, 'zzub_player_load_ccm'                  , c_int, ('player'  ,POINTER(zzub_player_t)),('fileName',c_char_p  ))
zzub_player_save_ccm                     = dlsym(libzzub, 'zzub_player_save_ccm'                  , c_int, ('player'  ,POINTER(zzub_player_t)),('fileName',c_char_p  ))
zzub_player_set_state                    = dlsym(libzzub, 'zzub_player_set_state'                 , None, ('player'  ,POINTER(zzub_player_t)),('state'   ,c_int     ))
zzub_player_get_state                    = dlsym(libzzub, 'zzub_player_get_state'                 , c_int, ('arg1'    ,POINTER(zzub_player_t)))
zzub_player_set_position                 = dlsym(libzzub, 'zzub_player_set_position'              , None, ('player'  ,POINTER(zzub_player_t)),('tick'    ,c_int     ))
zzub_player_get_bpm                      = dlsym(libzzub, 'zzub_player_get_bpm'                   , c_float, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_tpb                      = dlsym(libzzub, 'zzub_player_get_tpb'                   , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_set_bpm                      = dlsym(libzzub, 'zzub_player_set_bpm'                   , None, ('player'  ,POINTER(zzub_player_t)),('bpm'     ,c_float   ))
zzub_player_set_tpb                      = dlsym(libzzub, 'zzub_player_set_tpb'                   , None, ('player'  ,POINTER(zzub_player_t)),('tpb'     ,c_int     ))
zzub_player_get_pluginloader_count       = dlsym(libzzub, 'zzub_player_get_pluginloader_count'    , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_pluginloader             = dlsym(libzzub, 'zzub_player_get_pluginloader'          , POINTER(zzub_pluginloader_t), ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ))
zzub_player_get_pluginloader_by_name     = dlsym(libzzub, 'zzub_player_get_pluginloader_by_name'  , POINTER(zzub_pluginloader_t), ('player'  ,POINTER(zzub_player_t)),('name'    ,c_char_p  ))
zzub_player_get_plugin_count             = dlsym(libzzub, 'zzub_player_get_plugin_count'          , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_plugin                   = dlsym(libzzub, 'zzub_player_get_plugin'                , POINTER(zzub_plugin_t), ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ))
zzub_player_get_plugin_by_name           = dlsym(libzzub, 'zzub_player_get_plugin_by_name'        , POINTER(zzub_plugin_t), ('player'  ,POINTER(zzub_player_t)),('name'    ,c_char_p  ))
zzub_player_work_stereo                  = dlsym(libzzub, 'zzub_player_work_stereo'               , POINTER(POINTER(c_float)), ('player'  ,POINTER(zzub_player_t)),('numSamples',POINTER(c_int)))
zzub_player_clear                        = dlsym(libzzub, 'zzub_player_clear'                     , None, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_position                 = dlsym(libzzub, 'zzub_player_get_position'              , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_current_sequencer        = dlsym(libzzub, 'zzub_player_get_current_sequencer'     , POINTER(zzub_sequencer_t), ('player'  ,POINTER(zzub_player_t)))
zzub_player_set_current_sequencer        = dlsym(libzzub, 'zzub_player_set_current_sequencer'     , None, ('player'  ,POINTER(zzub_player_t)),('sequencer',POINTER(zzub_sequencer_t)))
zzub_player_get_loop_start               = dlsym(libzzub, 'zzub_player_get_loop_start'            , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_loop_end                 = dlsym(libzzub, 'zzub_player_get_loop_end'              , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_song_start               = dlsym(libzzub, 'zzub_player_get_song_start'            , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_set_loop_start               = dlsym(libzzub, 'zzub_player_set_loop_start'            , None, ('player'  ,POINTER(zzub_player_t)),('v'       ,c_int     ))
zzub_player_set_loop_end                 = dlsym(libzzub, 'zzub_player_set_loop_end'              , None, ('player'  ,POINTER(zzub_player_t)),('v'       ,c_int     ))
zzub_player_set_song_start               = dlsym(libzzub, 'zzub_player_set_song_start'            , None, ('player'  ,POINTER(zzub_player_t)),('v'       ,c_int     ))
zzub_player_get_song_end                 = dlsym(libzzub, 'zzub_player_get_song_end'              , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_set_song_end                 = dlsym(libzzub, 'zzub_player_set_song_end'              , None, ('player'  ,POINTER(zzub_player_t)),('v'       ,c_int     ))
zzub_player_lock_tick                    = dlsym(libzzub, 'zzub_player_lock_tick'                 , None, ('player'  ,POINTER(zzub_player_t)))
zzub_player_unlock_tick                  = dlsym(libzzub, 'zzub_player_unlock_tick'               , None, ('player'  ,POINTER(zzub_player_t)))
zzub_player_lock                         = dlsym(libzzub, 'zzub_player_lock'                      , None, ('player'  ,POINTER(zzub_player_t)))
zzub_player_unlock                       = dlsym(libzzub, 'zzub_player_unlock'                    , None, ('player'  ,POINTER(zzub_player_t)))
zzub_player_set_loop_enabled             = dlsym(libzzub, 'zzub_player_set_loop_enabled'          , None, ('player'  ,POINTER(zzub_player_t)),('enable'  ,c_int     ))
zzub_player_get_loop_enabled             = dlsym(libzzub, 'zzub_player_get_loop_enabled'          , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_sequence                 = dlsym(libzzub, 'zzub_player_get_sequence'              , POINTER(zzub_sequence_t), ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ))
zzub_player_get_sequence_count           = dlsym(libzzub, 'zzub_player_get_sequence_count'        , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_wave_count               = dlsym(libzzub, 'zzub_player_get_wave_count'            , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_wave                     = dlsym(libzzub, 'zzub_player_get_wave'                  , POINTER(zzub_wave_t), ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ))
zzub_player_play_wave                    = dlsym(libzzub, 'zzub_player_play_wave'                 , None, ('player'  ,POINTER(zzub_player_t)),('wave'    ,POINTER(zzub_wave_t)),('level'   ,c_int     ),('note'    ,c_int     ))
zzub_player_stop_wave                    = dlsym(libzzub, 'zzub_player_stop_wave'                 , None, ('player'  ,POINTER(zzub_player_t)))
zzub_player_set_wave_amp                 = dlsym(libzzub, 'zzub_player_set_wave_amp'              , None, ('player'  ,POINTER(zzub_player_t)),('amp'     ,c_float   ))
zzub_player_get_wave_amp                 = dlsym(libzzub, 'zzub_player_get_wave_amp'              , c_float, ('player'  ,POINTER(zzub_player_t)))
zzub_player_set_callback                 = dlsym(libzzub, 'zzub_player_set_callback'              , None, ('player'  ,POINTER(zzub_player_t)),('callback',ZzubCallback),('tag'     ,c_void_p  ))
zzub_player_handle_events                = dlsym(libzzub, 'zzub_player_handle_events'             , None, ('player'  ,POINTER(zzub_player_t)))
zzub_player_add_midimapping              = dlsym(libzzub, 'zzub_player_add_midimapping'           , POINTER(zzub_midimapping_t), ('player'  ,POINTER(zzub_player_t)),('plugin'  ,POINTER(zzub_plugin_t)),('group'   ,c_int     ),('track'   ,c_int     ),('param'   ,c_int     ),('channel' ,c_int     ),('controller',c_int     ))
zzub_player_remove_midimapping           = dlsym(libzzub, 'zzub_player_remove_midimapping'        , c_int, ('player'  ,POINTER(zzub_player_t)),('plugin'  ,POINTER(zzub_plugin_t)),('group'   ,c_int     ),('track'   ,c_int     ),('param'   ,c_int     ))
zzub_player_get_midimapping              = dlsym(libzzub, 'zzub_player_get_midimapping'           , POINTER(zzub_midimapping_t), ('player'  ,POINTER(zzub_player_t)),('index'   ,c_int     ))
zzub_player_get_midimapping_count        = dlsym(libzzub, 'zzub_player_get_midimapping_count'     , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_get_automation               = dlsym(libzzub, 'zzub_player_get_automation'            , c_int, ('player'  ,POINTER(zzub_player_t)))
zzub_player_set_automation               = dlsym(libzzub, 'zzub_player_set_automation'            , None, ('player'  ,POINTER(zzub_player_t)),('enable'  ,c_int     ))
zzub_player_get_infotext                 = dlsym(libzzub, 'zzub_player_get_infotext'              , c_char_p, ('player'  ,POINTER(zzub_player_t)))
zzub_player_set_infotext                 = dlsym(libzzub, 'zzub_player_set_infotext'              , None, ('player'  ,POINTER(zzub_player_t)),('text'    ,c_char_p  ))
zzub_player_set_midi_plugin              = dlsym(libzzub, 'zzub_player_set_midi_plugin'           , None, ('player'  ,POINTER(zzub_player_t)),('plugin'  ,POINTER(zzub_plugin_t)))
zzub_player_get_midi_plugin              = dlsym(libzzub, 'zzub_player_get_midi_plugin'           , POINTER(zzub_plugin_t), ('player'  ,POINTER(zzub_player_t)))
zzub_midimapping_get_plugin              = dlsym(libzzub, 'zzub_midimapping_get_plugin'           , POINTER(zzub_plugin_t), ('mapping' ,POINTER(zzub_midimapping_t)))
zzub_midimapping_get_group               = dlsym(libzzub, 'zzub_midimapping_get_group'            , c_int, ('mapping' ,POINTER(zzub_midimapping_t)))
zzub_midimapping_get_track               = dlsym(libzzub, 'zzub_midimapping_get_track'            , c_int, ('mapping' ,POINTER(zzub_midimapping_t)))
zzub_midimapping_get_column              = dlsym(libzzub, 'zzub_midimapping_get_column'           , c_int, ('mapping' ,POINTER(zzub_midimapping_t)))
zzub_midimapping_get_channel             = dlsym(libzzub, 'zzub_midimapping_get_channel'          , c_int, ('mapping' ,POINTER(zzub_midimapping_t)))
zzub_midimapping_get_controller          = dlsym(libzzub, 'zzub_midimapping_get_controller'       , c_int, ('mapping' ,POINTER(zzub_midimapping_t)))
zzub_pluginloader_get_name               = dlsym(libzzub, 'zzub_pluginloader_get_name'            , c_char_p, ('loader'  ,POINTER(zzub_pluginloader_t)))
zzub_pluginloader_get_short_name         = dlsym(libzzub, 'zzub_pluginloader_get_short_name'      , c_char_p, ('loader'  ,POINTER(zzub_pluginloader_t)))
zzub_pluginloader_get_parameter_count    = dlsym(libzzub, 'zzub_pluginloader_get_parameter_count' , c_int, ('loader'  ,POINTER(zzub_pluginloader_t)),('group'   ,c_int     ))
zzub_pluginloader_get_parameter          = dlsym(libzzub, 'zzub_pluginloader_get_parameter'       , POINTER(zzub_parameter_t), ('loader'  ,POINTER(zzub_pluginloader_t)),('group'   ,c_int     ),('index'   ,c_int     ))
zzub_pluginloader_get_attribute_count    = dlsym(libzzub, 'zzub_pluginloader_get_attribute_count' , c_int, ('loader'  ,POINTER(zzub_pluginloader_t)))
zzub_pluginloader_get_attribute          = dlsym(libzzub, 'zzub_pluginloader_get_attribute'       , POINTER(zzub_attribute_t), ('loader'  ,POINTER(zzub_pluginloader_t)),('index'   ,c_int     ))
zzub_pluginloader_get_loader_name        = dlsym(libzzub, 'zzub_pluginloader_get_loader_name'     , c_char_p, ('loader'  ,POINTER(zzub_pluginloader_t)))
zzub_pluginloader_get_flags              = dlsym(libzzub, 'zzub_pluginloader_get_flags'           , c_int, ('loader'  ,POINTER(zzub_pluginloader_t)))
zzub_pluginloader_get_uri                = dlsym(libzzub, 'zzub_pluginloader_get_uri'             , c_char_p, ('loader'  ,POINTER(zzub_pluginloader_t)))
zzub_pluginloader_get_author             = dlsym(libzzub, 'zzub_pluginloader_get_author'          , c_char_p, ('loader'  ,POINTER(zzub_pluginloader_t)))
zzub_parameter_get_type                  = dlsym(libzzub, 'zzub_parameter_get_type'               , c_int, ('param'   ,POINTER(zzub_parameter_t)))
zzub_parameter_get_name                  = dlsym(libzzub, 'zzub_parameter_get_name'               , c_char_p, ('param'   ,POINTER(zzub_parameter_t)))
zzub_parameter_get_description           = dlsym(libzzub, 'zzub_parameter_get_description'        , c_char_p, ('param'   ,POINTER(zzub_parameter_t)))
zzub_parameter_get_value_min             = dlsym(libzzub, 'zzub_parameter_get_value_min'          , c_int, ('param'   ,POINTER(zzub_parameter_t)))
zzub_parameter_get_value_max             = dlsym(libzzub, 'zzub_parameter_get_value_max'          , c_int, ('param'   ,POINTER(zzub_parameter_t)))
zzub_parameter_get_value_none            = dlsym(libzzub, 'zzub_parameter_get_value_none'         , c_int, ('param'   ,POINTER(zzub_parameter_t)))
zzub_parameter_get_value_default         = dlsym(libzzub, 'zzub_parameter_get_value_default'      , c_int, ('param'   ,POINTER(zzub_parameter_t)))
zzub_parameter_get_flags                 = dlsym(libzzub, 'zzub_parameter_get_flags'              , c_int, ('param'   ,POINTER(zzub_parameter_t)))
zzub_attribute_get_name                  = dlsym(libzzub, 'zzub_attribute_get_name'               , c_char_p, ('attrib'  ,POINTER(zzub_attribute_t)))
zzub_attribute_get_value_min             = dlsym(libzzub, 'zzub_attribute_get_value_min'          , c_int, ('attrib'  ,POINTER(zzub_attribute_t)))
zzub_attribute_get_value_max             = dlsym(libzzub, 'zzub_attribute_get_value_max'          , c_int, ('attrib'  ,POINTER(zzub_attribute_t)))
zzub_attribute_get_value_default         = dlsym(libzzub, 'zzub_attribute_get_value_default'      , c_int, ('attrib'  ,POINTER(zzub_attribute_t)))
zzub_player_create_plugin                = dlsym(libzzub, 'zzub_player_create_plugin'             , POINTER(zzub_plugin_t), ('player'  ,POINTER(zzub_player_t)),('input'   ,POINTER(zzub_input_t)),('dataSize',c_int     ),('instanceName',c_char_p  ),('loader'  ,POINTER(zzub_pluginloader_t)))
zzub_plugin_destroy                      = dlsym(libzzub, 'zzub_plugin_destroy'                   , c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_set_name                     = dlsym(libzzub, 'zzub_plugin_set_name'                  , c_int, ('machine' ,POINTER(zzub_plugin_t)),('name'    ,c_char_p  ))
zzub_plugin_get_name                     = dlsym(libzzub, 'zzub_plugin_get_name'                  , c_int, ('machine' ,POINTER(zzub_plugin_t)),('name'    ,c_char_p  ),('maxlen'  ,c_int     ))
zzub_plugin_get_commands                 = dlsym(libzzub, 'zzub_plugin_get_commands'              , c_int, ('machine' ,POINTER(zzub_plugin_t)),('commands',c_char_p  ),('maxlen'  ,c_int     ))
zzub_plugin_get_sub_commands             = dlsym(libzzub, 'zzub_plugin_get_sub_commands'          , c_int, ('machine' ,POINTER(zzub_plugin_t)),('i'       ,c_int     ),('commands',c_char_p  ),('maxlen'  ,c_int     ))
zzub_plugin_command                      = dlsym(libzzub, 'zzub_plugin_command'                   , None, ('machine' ,POINTER(zzub_plugin_t)),('i'       ,c_int     ))
zzub_plugin_get_flags                    = dlsym(libzzub, 'zzub_plugin_get_flags'                 , c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_get_output_channels          = dlsym(libzzub, 'zzub_plugin_get_output_channels'       , c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_get_pluginloader             = dlsym(libzzub, 'zzub_plugin_get_pluginloader'          , POINTER(zzub_pluginloader_t), ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_add_pattern                  = dlsym(libzzub, 'zzub_plugin_add_pattern'               , None, ('machine' ,POINTER(zzub_plugin_t)),('pattern' ,POINTER(zzub_pattern_t)))
zzub_plugin_remove_pattern               = dlsym(libzzub, 'zzub_plugin_remove_pattern'            , None, ('machine' ,POINTER(zzub_plugin_t)),('pattern' ,POINTER(zzub_pattern_t)))
zzub_plugin_move_pattern                 = dlsym(libzzub, 'zzub_plugin_move_pattern'              , None, ('machine' ,POINTER(zzub_plugin_t)),('index'   ,c_int     ),('newIndex',c_int     ))
zzub_plugin_get_pattern                  = dlsym(libzzub, 'zzub_plugin_get_pattern'               , POINTER(zzub_pattern_t), ('machine' ,POINTER(zzub_plugin_t)),('index'   ,c_int     ))
zzub_plugin_get_pattern_index            = dlsym(libzzub, 'zzub_plugin_get_pattern_index'         , c_int, ('machine' ,POINTER(zzub_plugin_t)),('pattern' ,POINTER(zzub_pattern_t)))
zzub_plugin_get_pattern_by_name          = dlsym(libzzub, 'zzub_plugin_get_pattern_by_name'       , POINTER(zzub_pattern_t), ('machine' ,POINTER(zzub_plugin_t)),('name'    ,c_char_p  ))
zzub_plugin_get_pattern_count            = dlsym(libzzub, 'zzub_plugin_get_pattern_count'         , c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_get_parameter_value          = dlsym(libzzub, 'zzub_plugin_get_parameter_value'       , c_int, ('machine' ,POINTER(zzub_plugin_t)),('group'   ,c_int     ),('track'   ,c_int     ),('column'  ,c_int     ))
zzub_plugin_describe_value               = dlsym(libzzub, 'zzub_plugin_describe_value'            , c_int, ('machine' ,POINTER(zzub_plugin_t)),('group'   ,c_int     ),('column'  ,c_int     ),('value'   ,c_int     ),('name'    ,c_char_p  ),('maxlen'  ,c_int     ))
zzub_plugin_set_parameter_value          = dlsym(libzzub, 'zzub_plugin_set_parameter_value'       , None, ('machine' ,POINTER(zzub_plugin_t)),('group'   ,c_int     ),('track'   ,c_int     ),('column'  ,c_int     ),('value'   ,c_int     ),('record'  ,c_int     ))
zzub_plugin_get_position                 = dlsym(libzzub, 'zzub_plugin_get_position'              , None, ('machine' ,POINTER(zzub_plugin_t)),('x'       ,POINTER(c_float)),('y'       ,POINTER(c_float)))
zzub_plugin_set_position                 = dlsym(libzzub, 'zzub_plugin_set_position'              , None, ('machine' ,POINTER(zzub_plugin_t)),('x'       ,c_float   ),('y'       ,c_float   ))
zzub_plugin_get_input_connection_count   = dlsym(libzzub, 'zzub_plugin_get_input_connection_count', c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_get_input_connection         = dlsym(libzzub, 'zzub_plugin_get_input_connection'      , POINTER(zzub_connection_t), ('machine' ,POINTER(zzub_plugin_t)),('index'   ,c_int     ))
zzub_plugin_get_output_connection_count  = dlsym(libzzub, 'zzub_plugin_get_output_connection_count', c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_get_output_connection        = dlsym(libzzub, 'zzub_plugin_get_output_connection'     , POINTER(zzub_connection_t), ('machine' ,POINTER(zzub_plugin_t)),('index'   ,c_int     ))
zzub_plugin_get_last_peak                = dlsym(libzzub, 'zzub_plugin_get_last_peak'             , None, ('machine' ,POINTER(zzub_plugin_t)),('maxL'    ,POINTER(c_float)),('maxR'    ,POINTER(c_float)))
zzub_plugin_add_audio_input              = dlsym(libzzub, 'zzub_plugin_add_audio_input'           , POINTER(zzub_connection_t), ('machine' ,POINTER(zzub_plugin_t)),('fromMachine',POINTER(zzub_plugin_t)),('amp'     ,c_ushort  ),('pan'     ,c_ushort  ))
zzub_plugin_add_event_input              = dlsym(libzzub, 'zzub_plugin_add_event_input'           , POINTER(zzub_connection_t), ('machine' ,POINTER(zzub_plugin_t)),('fromMachine',POINTER(zzub_plugin_t)))
zzub_plugin_delete_input                 = dlsym(libzzub, 'zzub_plugin_delete_input'              , None, ('machine' ,POINTER(zzub_plugin_t)),('fromMachine',POINTER(zzub_plugin_t)))
zzub_plugin_set_input_channels           = dlsym(libzzub, 'zzub_plugin_set_input_channels'        , None, ('machine' ,POINTER(zzub_plugin_t)),('fromMachine',POINTER(zzub_plugin_t)),('channels',c_int     ))
zzub_plugin_get_track_count              = dlsym(libzzub, 'zzub_plugin_get_track_count'           , c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_set_track_count              = dlsym(libzzub, 'zzub_plugin_set_track_count'           , None, ('machine' ,POINTER(zzub_plugin_t)),('count'   ,c_int     ))
zzub_plugin_get_mute                     = dlsym(libzzub, 'zzub_plugin_get_mute'                  , c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_set_mute                     = dlsym(libzzub, 'zzub_plugin_set_mute'                  , None, ('machine' ,POINTER(zzub_plugin_t)),('muted'   ,c_int     ))
zzub_plugin_get_mixbuffer                = dlsym(libzzub, 'zzub_plugin_get_mixbuffer'             , c_int, ('machine' ,POINTER(zzub_plugin_t)),('leftbuffer',POINTER(c_float)),('rightbuffer',POINTER(c_float)),('size'    ,POINTER(c_int)),('samplepos',POINTER(c_longlong)))
zzub_plugin_set_wave_file_path           = dlsym(libzzub, 'zzub_plugin_set_wave_file_path'        , c_int, ('machine' ,POINTER(zzub_plugin_t)),('path'    ,c_char_p  ))
zzub_plugin_get_wave_file_path           = dlsym(libzzub, 'zzub_plugin_get_wave_file_path'        , c_char_p, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_set_write_wave               = dlsym(libzzub, 'zzub_plugin_set_write_wave'            , None, ('machine' ,POINTER(zzub_plugin_t)),('enable'  ,c_int     ))
zzub_plugin_get_write_wave               = dlsym(libzzub, 'zzub_plugin_get_write_wave'            , c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_set_start_write_position     = dlsym(libzzub, 'zzub_plugin_set_start_write_position'  , None, ('machine' ,POINTER(zzub_plugin_t)),('position',c_int     ))
zzub_plugin_set_end_write_position       = dlsym(libzzub, 'zzub_plugin_set_end_write_position'    , None, ('machine' ,POINTER(zzub_plugin_t)),('position',c_int     ))
zzub_plugin_get_start_write_position     = dlsym(libzzub, 'zzub_plugin_get_start_write_position'  , c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_get_end_write_position       = dlsym(libzzub, 'zzub_plugin_get_end_write_position'    , c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_set_auto_write               = dlsym(libzzub, 'zzub_plugin_set_auto_write'            , None, ('machine' ,POINTER(zzub_plugin_t)),('enable'  ,c_int     ))
zzub_plugin_get_auto_write               = dlsym(libzzub, 'zzub_plugin_get_auto_write'            , c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_get_ticks_written            = dlsym(libzzub, 'zzub_plugin_get_ticks_written'         , c_int, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_reset_ticks_written          = dlsym(libzzub, 'zzub_plugin_reset_ticks_written'       , None, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_invoke_event                 = dlsym(libzzub, 'zzub_plugin_invoke_event'              , c_int, ('machine' ,POINTER(zzub_plugin_t)),('data'    ,POINTER(zzub_event_data_t)),('immediate',c_int     ))
zzub_plugin_get_last_worktime            = dlsym(libzzub, 'zzub_plugin_get_last_worktime'         , c_double, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_tick                         = dlsym(libzzub, 'zzub_plugin_tick'                      , None, ('machine' ,POINTER(zzub_plugin_t)))
zzub_plugin_get_attribute_value          = dlsym(libzzub, 'zzub_plugin_get_attribute_value'       , c_int, ('machine' ,POINTER(zzub_plugin_t)),('index'   ,c_int     ))
zzub_plugin_set_attribute_value          = dlsym(libzzub, 'zzub_plugin_set_attribute_value'       , None, ('machine' ,POINTER(zzub_plugin_t)),('index'   ,c_int     ),('value'   ,c_int     ))
zzub_plugin_get_new_pattern_name         = dlsym(libzzub, 'zzub_plugin_get_new_pattern_name'      , None, ('machine' ,POINTER(zzub_plugin_t)),('name'    ,c_char_p  ),('maxLen'  ,c_int     ))
zzub_plugin_add_post_process             = dlsym(libzzub, 'zzub_plugin_add_post_process'          , POINTER(zzub_postprocess_t), ('machine' ,POINTER(zzub_plugin_t)),('mixcallback',ZzubMixCallback),('tag'     ,c_void_p  ))
zzub_plugin_remove_post_process          = dlsym(libzzub, 'zzub_plugin_remove_post_process'       , None, ('machine' ,POINTER(zzub_plugin_t)),('pp'      ,POINTER(zzub_postprocess_t)))
zzub_plugin_play_midi_note               = dlsym(libzzub, 'zzub_plugin_play_midi_note'            , None, ('plugin'  ,POINTER(zzub_plugin_t)),('note'    ,c_int     ),('prevNote',c_int     ),('velocity',c_int     ))
zzub_connection_get_input                = dlsym(libzzub, 'zzub_connection_get_input'             , POINTER(zzub_plugin_t), ('connection',POINTER(zzub_connection_t)))
zzub_connection_get_output               = dlsym(libzzub, 'zzub_connection_get_output'            , POINTER(zzub_plugin_t), ('connection',POINTER(zzub_connection_t)))
zzub_connection_get_type                 = dlsym(libzzub, 'zzub_connection_get_type'              , c_int, ('connection',POINTER(zzub_connection_t)))
zzub_connection_get_audio_connection     = dlsym(libzzub, 'zzub_connection_get_audio_connection'  , POINTER(zzub_audio_connection_t), ('connection',POINTER(zzub_connection_t)))
zzub_connection_get_event_connection     = dlsym(libzzub, 'zzub_connection_get_event_connection'  , POINTER(zzub_event_connection_t), ('connection',POINTER(zzub_connection_t)))
zzub_audio_connection_get_amplitude      = dlsym(libzzub, 'zzub_audio_connection_get_amplitude'   , c_ushort, ('connection',POINTER(zzub_audio_connection_t)))
zzub_audio_connection_get_panning        = dlsym(libzzub, 'zzub_audio_connection_get_panning'     , c_ushort, ('connection',POINTER(zzub_audio_connection_t)))
zzub_audio_connection_set_amplitude      = dlsym(libzzub, 'zzub_audio_connection_set_amplitude'   , None, ('connection',POINTER(zzub_audio_connection_t)),('amp'     ,c_ushort  ))
zzub_audio_connection_set_panning        = dlsym(libzzub, 'zzub_audio_connection_set_panning'     , None, ('connection',POINTER(zzub_audio_connection_t)),('pan'     ,c_ushort  ))
zzub_event_connection_add_binding        = dlsym(libzzub, 'zzub_event_connection_add_binding'     , c_int, ('connection',POINTER(zzub_event_connection_t)),('sourceparam',c_int     ),('targetgroup',c_int     ),('targettrack',c_int     ),('targetparam',c_int     ))
zzub_event_connection_get_binding_count  = dlsym(libzzub, 'zzub_event_connection_get_binding_count', c_int, ('connection',POINTER(zzub_event_connection_t)))
zzub_event_connection_get_binding        = dlsym(libzzub, 'zzub_event_connection_get_binding'     , POINTER(zzub_event_connection_binding_t), ('connection',POINTER(zzub_event_connection_t)),('index'   ,c_int     ))
zzub_event_connection_remove_binding     = dlsym(libzzub, 'zzub_event_connection_remove_binding'  , c_int, ('connection',POINTER(zzub_event_connection_t)),('index'   ,c_int     ))
zzub_event_connection_binding_get_group  = dlsym(libzzub, 'zzub_event_connection_binding_get_group', c_int, ('binding' ,POINTER(zzub_event_connection_binding_t)))
zzub_event_connection_binding_get_track  = dlsym(libzzub, 'zzub_event_connection_binding_get_track', c_int, ('binding' ,POINTER(zzub_event_connection_binding_t)))
zzub_event_connection_binding_get_column = dlsym(libzzub, 'zzub_event_connection_binding_get_column', c_int, ('binding' ,POINTER(zzub_event_connection_binding_t)))
zzub_event_connection_binding_get_controller = dlsym(libzzub, 'zzub_event_connection_binding_get_controller', c_int, ('binding' ,POINTER(zzub_event_connection_binding_t)))
zzub_sequencer_destroy                   = dlsym(libzzub, 'zzub_sequencer_destroy'                , None, ('sequencer',POINTER(zzub_sequencer_t)))
zzub_sequencer_create_range              = dlsym(libzzub, 'zzub_sequencer_create_range'           , POINTER(zzub_sequencer_t), ('sequencer',POINTER(zzub_sequencer_t)),('fromRow' ,c_int     ),('fromTrack',c_int     ),('toRow'   ,c_int     ),('toTrack' ,c_int     ))
zzub_sequencer_get_track_count           = dlsym(libzzub, 'zzub_sequencer_get_track_count'        , c_int, ('sequencer',POINTER(zzub_sequencer_t)))
zzub_sequencer_get_track                 = dlsym(libzzub, 'zzub_sequencer_get_track'              , POINTER(zzub_sequence_t), ('sequencer',POINTER(zzub_sequencer_t)),('index'   ,c_int     ))
zzub_sequencer_move_track                = dlsym(libzzub, 'zzub_sequencer_move_track'             , None, ('sequencer',POINTER(zzub_sequencer_t)),('index'   ,c_int     ),('newIndex',c_int     ))
zzub_sequencer_create_track              = dlsym(libzzub, 'zzub_sequencer_create_track'           , POINTER(zzub_sequence_t), ('sequencer',POINTER(zzub_sequencer_t)),('machine' ,POINTER(zzub_plugin_t)))
zzub_sequencer_remove_track              = dlsym(libzzub, 'zzub_sequencer_remove_track'           , None, ('sequencer',POINTER(zzub_sequencer_t)),('index'   ,c_int     ))
zzub_sequence_get_value_at               = dlsym(libzzub, 'zzub_sequence_get_value_at'            , c_ulong, ('track'   ,POINTER(zzub_sequence_t)),('pos'     ,c_ulong   ),('exists'  ,POINTER(c_int)))
zzub_sequence_set_event                  = dlsym(libzzub, 'zzub_sequence_set_event'               , None, ('track'   ,POINTER(zzub_sequence_t)),('pos'     ,c_ulong   ),('value'   ,c_ulong   ))
zzub_sequence_get_event_count            = dlsym(libzzub, 'zzub_sequence_get_event_count'         , c_int, ('track'   ,POINTER(zzub_sequence_t)))
zzub_sequence_get_event                  = dlsym(libzzub, 'zzub_sequence_get_event'               , c_int, ('track'   ,POINTER(zzub_sequence_t)),('index'   ,c_int     ),('pos'     ,POINTER(c_ulong)),('value'   ,POINTER(c_ulong)))
zzub_sequence_move_events                = dlsym(libzzub, 'zzub_sequence_move_events'             , None, ('track'   ,POINTER(zzub_sequence_t)),('fromRow' ,c_ulong   ),('delta'   ,c_ulong   ))
zzub_sequence_get_plugin                 = dlsym(libzzub, 'zzub_sequence_get_plugin'              , POINTER(zzub_plugin_t), ('track'   ,POINTER(zzub_sequence_t)))
zzub_sequence_remove_event_at            = dlsym(libzzub, 'zzub_sequence_remove_event_at'         , None, ('track'   ,POINTER(zzub_sequence_t)),('pos'     ,c_ulong   ))
zzub_sequence_remove_event_range         = dlsym(libzzub, 'zzub_sequence_remove_event_range'      , None, ('track'   ,POINTER(zzub_sequence_t)),('from_pos',c_ulong   ),('to_pos'  ,c_ulong   ))
zzub_sequence_remove_event_value         = dlsym(libzzub, 'zzub_sequence_remove_event_value'      , None, ('track'   ,POINTER(zzub_sequence_t)),('value'   ,c_ulong   ))
zzub_plugin_create_pattern               = dlsym(libzzub, 'zzub_plugin_create_pattern'            , POINTER(zzub_pattern_t), ('machine' ,POINTER(zzub_plugin_t)),('row'     ,c_int     ))
zzub_pattern_destroy                     = dlsym(libzzub, 'zzub_pattern_destroy'                  , None, ('pattern' ,POINTER(zzub_pattern_t)))
zzub_pattern_get_name                    = dlsym(libzzub, 'zzub_pattern_get_name'                 , None, ('pattern' ,POINTER(zzub_pattern_t)),('name'    ,c_char_p  ),('maxLen'  ,c_int     ))
zzub_pattern_set_name                    = dlsym(libzzub, 'zzub_pattern_set_name'                 , None, ('pattern' ,POINTER(zzub_pattern_t)),('name'    ,c_char_p  ))
zzub_pattern_set_row_count               = dlsym(libzzub, 'zzub_pattern_set_row_count'            , None, ('pattern' ,POINTER(zzub_pattern_t)),('rows'    ,c_int     ))
zzub_pattern_get_row_count               = dlsym(libzzub, 'zzub_pattern_get_row_count'            , c_int, ('pattern' ,POINTER(zzub_pattern_t)))
zzub_pattern_insert_row                  = dlsym(libzzub, 'zzub_pattern_insert_row'               , None, ('pattern' ,POINTER(zzub_pattern_t)),('group'   ,c_int     ),('track'   ,c_int     ),('column'  ,c_int     ),('row'     ,c_int     ))
zzub_pattern_delete_row                  = dlsym(libzzub, 'zzub_pattern_delete_row'               , None, ('pattern' ,POINTER(zzub_pattern_t)),('group'   ,c_int     ),('track'   ,c_int     ),('column'  ,c_int     ),('row'     ,c_int     ))
zzub_pattern_get_track                   = dlsym(libzzub, 'zzub_pattern_get_track'                , POINTER(zzub_patterntrack_t), ('pattern' ,POINTER(zzub_pattern_t)),('index'   ,c_int     ))
zzub_pattern_get_track_count             = dlsym(libzzub, 'zzub_pattern_get_track_count'          , c_int, ('pattern' ,POINTER(zzub_pattern_t)))
zzub_pattern_get_value                   = dlsym(libzzub, 'zzub_pattern_get_value'                , c_int, ('pattern' ,POINTER(zzub_pattern_t)),('row'     ,c_int     ),('group'   ,c_int     ),('track'   ,c_int     ),('column'  ,c_int     ))
zzub_pattern_set_value                   = dlsym(libzzub, 'zzub_pattern_set_value'                , None, ('pattern' ,POINTER(zzub_pattern_t)),('row'     ,c_int     ),('group'   ,c_int     ),('track'   ,c_int     ),('column'  ,c_int     ),('value'   ,c_int     ))
zzub_pattern_get_bandwidth_digest        = dlsym(libzzub, 'zzub_pattern_get_bandwidth_digest'     , None, ('pattern' ,POINTER(zzub_pattern_t)),('digest'  ,POINTER(c_float)),('digestsize',c_int     ))
zzub_wave_get_level_count                = dlsym(libzzub, 'zzub_wave_get_level_count'             , c_int, ('wave'    ,POINTER(zzub_wave_t)))
zzub_wave_get_level                      = dlsym(libzzub, 'zzub_wave_get_level'                   , POINTER(zzub_wavelevel_t), ('wave'    ,POINTER(zzub_wave_t)),('index'   ,c_int     ))
zzub_wave_get_name                       = dlsym(libzzub, 'zzub_wave_get_name'                    , c_char_p, ('wave'    ,POINTER(zzub_wave_t)))
zzub_wave_get_path                       = dlsym(libzzub, 'zzub_wave_get_path'                    , c_char_p, ('wave'    ,POINTER(zzub_wave_t)))
zzub_wave_get_flags                      = dlsym(libzzub, 'zzub_wave_get_flags'                   , c_int, ('wave'    ,POINTER(zzub_wave_t)))
zzub_wave_get_volume                     = dlsym(libzzub, 'zzub_wave_get_volume'                  , c_float, ('wave'    ,POINTER(zzub_wave_t)))
zzub_wave_clear                          = dlsym(libzzub, 'zzub_wave_clear'                       , None, ('wave'    ,POINTER(zzub_wave_t)))
zzub_wave_load_sample                    = dlsym(libzzub, 'zzub_wave_load_sample'                 , c_int, ('wave'    ,POINTER(zzub_wave_t)),('level'   ,c_int     ),('path'    ,c_char_p  ))
zzub_wave_save_sample                    = dlsym(libzzub, 'zzub_wave_save_sample'                 , c_int, ('wave'    ,POINTER(zzub_wave_t)),('level'   ,c_int     ),('path'    ,c_char_p  ))
zzub_wave_set_volume                     = dlsym(libzzub, 'zzub_wave_set_volume'                  , None, ('wave'    ,POINTER(zzub_wave_t)),('volume'  ,c_float   ))
zzub_wave_set_path                       = dlsym(libzzub, 'zzub_wave_set_path'                    , None, ('wave'    ,POINTER(zzub_wave_t)),('path'    ,c_char_p  ))
zzub_wave_set_name                       = dlsym(libzzub, 'zzub_wave_set_name'                    , None, ('wave'    ,POINTER(zzub_wave_t)),('name'    ,c_char_p  ))
zzub_wave_set_flags                      = dlsym(libzzub, 'zzub_wave_set_flags'                   , None, ('wave'    ,POINTER(zzub_wave_t)),('flags'   ,c_int     ))
zzub_wave_get_envelope_count             = dlsym(libzzub, 'zzub_wave_get_envelope_count'          , c_int, ('wave'    ,POINTER(zzub_wave_t)))
zzub_wave_get_envelope                   = dlsym(libzzub, 'zzub_wave_get_envelope'                , POINTER(zzub_envelope_t), ('wave'    ,POINTER(zzub_wave_t)),('index'   ,c_int     ))
zzub_wavelevel_get_sample_count          = dlsym(libzzub, 'zzub_wavelevel_get_sample_count'       , c_int, ('level'   ,POINTER(zzub_wavelevel_t)))
zzub_wavelevel_get_samples               = dlsym(libzzub, 'zzub_wavelevel_get_samples'            , c_void_p, ('level'   ,POINTER(zzub_wavelevel_t)))
zzub_wavelevel_get_samples_digest        = dlsym(libzzub, 'zzub_wavelevel_get_samples_digest'     , None, ('level'   ,POINTER(zzub_wavelevel_t)),('channel' ,c_int     ),('start'   ,c_int     ),('end'     ,c_int     ),('mindigest',POINTER(c_float)),('maxdigest',POINTER(c_float)),('ampdigest',POINTER(c_float)),('digestsize',c_int     ))
zzub_wavelevel_get_root_note             = dlsym(libzzub, 'zzub_wavelevel_get_root_note'          , c_int, ('level'   ,POINTER(zzub_wavelevel_t)))
zzub_wavelevel_get_samples_per_second    = dlsym(libzzub, 'zzub_wavelevel_get_samples_per_second' , c_int, ('level'   ,POINTER(zzub_wavelevel_t)))
zzub_wavelevel_get_loop_start            = dlsym(libzzub, 'zzub_wavelevel_get_loop_start'         , c_int, ('level'   ,POINTER(zzub_wavelevel_t)))
zzub_wavelevel_get_loop_end              = dlsym(libzzub, 'zzub_wavelevel_get_loop_end'           , c_int, ('level'   ,POINTER(zzub_wavelevel_t)))
zzub_wavelevel_set_root_note             = dlsym(libzzub, 'zzub_wavelevel_set_root_note'          , None, ('level'   ,POINTER(zzub_wavelevel_t)),('rootnote',c_int     ))
zzub_wavelevel_set_samples_per_second    = dlsym(libzzub, 'zzub_wavelevel_set_samples_per_second' , None, ('level'   ,POINTER(zzub_wavelevel_t)),('samplespersecond',c_int     ))
zzub_wavelevel_set_loop_start            = dlsym(libzzub, 'zzub_wavelevel_set_loop_start'         , None, ('level'   ,POINTER(zzub_wavelevel_t)),('loopstart',c_int     ))
zzub_wavelevel_set_loop_end              = dlsym(libzzub, 'zzub_wavelevel_set_loop_end'           , None, ('level'   ,POINTER(zzub_wavelevel_t)),('loopend' ,c_int     ))
zzub_wavelevel_silence_range             = dlsym(libzzub, 'zzub_wavelevel_silence_range'          , c_int, ('level'   ,POINTER(zzub_wavelevel_t)),('start'   ,c_int     ),('end'     ,c_int     ))
zzub_wavelevel_remove_range              = dlsym(libzzub, 'zzub_wavelevel_remove_range'           , c_int, ('level'   ,POINTER(zzub_wavelevel_t)),('start'   ,c_int     ),('end'     ,c_int     ))
zzub_wavelevel_insert                    = dlsym(libzzub, 'zzub_wavelevel_insert'                 , c_int, ('level'   ,POINTER(zzub_wavelevel_t)),('start'   ,c_int     ),('sampleData',c_void_p  ),('channels',c_int     ),('waveFormat',c_int     ),('numSamples',c_int     ))
zzub_wavelevel_get_format                = dlsym(libzzub, 'zzub_wavelevel_get_format'             , c_int, ('level'   ,POINTER(zzub_wavelevel_t)))
zzub_envelope_get_attack                 = dlsym(libzzub, 'zzub_envelope_get_attack'              , c_ushort, ('env'     ,POINTER(zzub_envelope_t)))
zzub_envelope_get_decay                  = dlsym(libzzub, 'zzub_envelope_get_decay'               , c_ushort, ('env'     ,POINTER(zzub_envelope_t)))
zzub_envelope_get_sustain                = dlsym(libzzub, 'zzub_envelope_get_sustain'             , c_ushort, ('env'     ,POINTER(zzub_envelope_t)))
zzub_envelope_get_release                = dlsym(libzzub, 'zzub_envelope_get_release'             , c_ushort, ('env'     ,POINTER(zzub_envelope_t)))
zzub_envelope_set_attack                 = dlsym(libzzub, 'zzub_envelope_set_attack'              , None, ('env'     ,POINTER(zzub_envelope_t)),('attack'  ,c_ushort  ))
zzub_envelope_set_decay                  = dlsym(libzzub, 'zzub_envelope_set_decay'               , None, ('env'     ,POINTER(zzub_envelope_t)),('decay'   ,c_ushort  ))
zzub_envelope_set_sustain                = dlsym(libzzub, 'zzub_envelope_set_sustain'             , None, ('env'     ,POINTER(zzub_envelope_t)),('sustain' ,c_ushort  ))
zzub_envelope_set_release                = dlsym(libzzub, 'zzub_envelope_set_release'             , None, ('env'     ,POINTER(zzub_envelope_t)),('release' ,c_ushort  ))
zzub_envelope_get_subdivision            = dlsym(libzzub, 'zzub_envelope_get_subdivision'         , c_char, ('env'     ,POINTER(zzub_envelope_t)))
zzub_envelope_set_subdivision            = dlsym(libzzub, 'zzub_envelope_set_subdivision'         , None, ('env'     ,POINTER(zzub_envelope_t)),('subdiv'  ,c_char    ))
zzub_envelope_get_flags                  = dlsym(libzzub, 'zzub_envelope_get_flags'               , c_char, ('env'     ,POINTER(zzub_envelope_t)))
zzub_envelope_set_flags                  = dlsym(libzzub, 'zzub_envelope_set_flags'               , None, ('env'     ,POINTER(zzub_envelope_t)),('flags'   ,c_char    ))
zzub_envelope_is_enabled                 = dlsym(libzzub, 'zzub_envelope_is_enabled'              , c_int, ('env'     ,POINTER(zzub_envelope_t)))
zzub_envelope_enable                     = dlsym(libzzub, 'zzub_envelope_enable'                  , None, ('env'     ,POINTER(zzub_envelope_t)),('enable'  ,c_int     ))
zzub_envelope_get_point_count            = dlsym(libzzub, 'zzub_envelope_get_point_count'         , c_int, ('env'     ,POINTER(zzub_envelope_t)))
zzub_envelope_get_point                  = dlsym(libzzub, 'zzub_envelope_get_point'               , None, ('env'     ,POINTER(zzub_envelope_t)),('index'   ,c_int     ),('x'       ,POINTER(c_ushort)),('y'       ,POINTER(c_ushort)),('flags'   ,POINTER(c_ubyte)))
zzub_envelope_set_point                  = dlsym(libzzub, 'zzub_envelope_set_point'               , None, ('env'     ,POINTER(zzub_envelope_t)),('index'   ,c_int     ),('x'       ,c_ushort  ),('y'       ,c_ushort  ),('flags'   ,c_ubyte   ))
zzub_envelope_insert_point               = dlsym(libzzub, 'zzub_envelope_insert_point'            , None, ('env'     ,POINTER(zzub_envelope_t)),('index'   ,c_int     ))
zzub_envelope_delete_point               = dlsym(libzzub, 'zzub_envelope_delete_point'            , None, ('env'     ,POINTER(zzub_envelope_t)),('index'   ,c_int     ))
