#encoding: latin-1

# Neil
# Modular Sequencer
# Copyright (C) 2006 The Neil Development Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Import('env','install')
import glob, os

#######################################
#
# neil extensions
#
#######################################

# this code basically just scans subdirectories for additional sconscript files
# and also provides a context for that sconscript to install a pluginview.

pluginview_dir_path = ""
pvenv = None
pvbasename = None

def install_extension(source):
        install('${NEIL_INSTALL_PATH}/pluginviews/' + pvbasename, source)

for filename in os.listdir('.'):
        pluginview_dir_path = os.path.abspath(filename)
        if os.path.isfile(os.path.join(pluginview_dir_path,'SConscript')):    
                pvbasename = filename
                pvenv = env.Copy()
                Export('pluginview_dir_path','pvenv','install_extension')
                env.SConscript(os.path.join(pluginview_dir_path,'SConscript'))
