Import('pluginenv', 'build_plugin')

localenv = pluginenv.Clone()
localenv.Append(CPPPATH=["${LANTERNFISH_SRC_PATH}"])
localenv.Append(LIBS=['lanternfish'])
localenv.Append(CPPFLAGS=['-O3'])

files = ["FM303.cpp"]

build_plugin(localenv, "somono_fm303", files)
	     
