Import('pluginenv', 'build_plugin')

localenv = pluginenv.Clone()

# # localenv.Append(CCFLAGS = '-g')

# def CheckPKGConfig(context, version):
#      context.Message( 'Checking for pkg-config... ' )
#      ret = context.TryAction('pkg-config --atleast-pkgconfig-version=%s' % version)[0]
#      context.Result( ret )
#      return ret

# def CheckPKG(context, name):
#      context.Message( 'Checking for %s... ' % name )
#      ret = context.TryAction('pkg-config --exists \'%s\'' % name)[0]
#      context.Result( ret )
#      return ret

# # Configuration:

# conf = Configure(localenv, custom_tests = { 'CheckPKGConfig' : CheckPKGConfig,
#                                        'CheckPKG' : CheckPKG })

# if not conf.CheckPKGConfig('0.15.0'):
#      print 'pkg-config >= 0.15.0 not found.'
#      Exit(1)

# if not conf.CheckPKG('gtk+-2.0 >= 2.4'):
#      print 'gtk+-2.0 >= 2.4 not found.'
#      Exit(1)

# if not conf.CheckPKG('gthread-2.0 >= 2.30.0'):
#      print 'gthread-2.0 >= 2.30.0 not found.'
#      Exit(1)

# localenv = conf.Finish()

# localenv.ParseConfig('pkg-config --cflags --libs gtk+-2.0 gthread-2.0')

localenv.Append(CCFLAGS = '-pthread -g -pedantic -Wall')

localenv.Append(LIBS = ["X11", "gdkglext-x11-1.0"] );
localenv.Append(CCFLAGS=' `pkg-config --cflags x11 gtk+-2.0 glib-2.0 gthread-2.0 gtkglext-1.0` ')
localenv.Append(LINKFLAGS=' `pkg-config --libs x11 gtk+-2.0 glib-2.0 gthread-2.0 gtkglext-1.0` ')

files = ["Oscilloscope.cpp", "Renderer.cpp"]

build_plugin(localenv, "gershon_oscilloscope", files)
