#!/usr/bin/env python

CLEAN = [
	'*.pyc',
]

import os,glob
for base,folders,filenames in os.walk('.'):
	if '.svn' in base:
		continue
	for ext in CLEAN:
		for filename in glob.glob(os.path.join(base, ext)):
			print "removing "+filename+"..."
			os.remove(filename)