#encoding: latin-1

# bmp-ccm
# libzzub plugin for beep media player
# Copyright (C) 2006 The Aldrin Development Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

################################################
#
# ccm input plugin for beep media player
#
################################################

Import('env', 'posix', 'install')

if env['BMPCCM'] == True:
	files = [
		'plugin.c',
	]

	localenv = env.Copy()
	localenv.Append(LIBS=[
		'zzub',
	])
	
	localenv.ParseConfig('pkg-config --cflags --libs gtk+-2.0')

	bmpccm = localenv.SharedLibrary('${LIB_BUILD_PATH}/bmp/Input/ccm', files)
	install("${DESTDIR}${PREFIX}${LIBDIR}/bmp/Input", bmpccm)
