#!/usr/bin/env python

import os,sys

os.environ['LIBRARY_LOAD_NONE'] = 'true'

os.system('rm -rf aldrinapi')

command = [
'epydoc',
'-v',
'--html',
'-n',
'"Aldrin API"',
'--url',
'http://www.aldrin.eu',
'-o',
'./aldrinapi',
'--debug',
'--graph',
'all',
'--inheritance',
'grouped',
'--css',
'./style.css',
]

paths = [
	'../src/aldrin',
	'../src/components'
]
for basepath in paths:
	for filename in os.listdir(basepath):
		if filename.endswith('.py'):
			filename = os.path.join(basepath,filename)
			command.append(filename)

cmd = ' '.join(command)
print cmd
os.system(cmd)
