Import('pluginenv', 'build_plugin')

localenv = pluginenv.Clone()
localenv.Append(CPPPATH=["${LANTERNFISH_SRC_PATH}"])
localenv.Append(LIBS=['lanternfish'])
localenv.Append(CPPFLAGS=['-O3'])

files = ["Cloud.cpp", "ACloud.cpp", "Grain.cpp"]

build_plugin(localenv, "somono_cloud", files)
	     
