Import('pluginenv', 'build_plugin')

localenv = pluginenv.Copy()
localenv.Append(CPPPATH=["${LANTERNFISH_SRC_PATH}"])
localenv.Append(LIBS=['lanternfish'])

files = ["Cloud.cpp", "ACloud.cpp", "Grain.cpp"]

build_plugin(localenv, "somono_cloud", files, helpfiles=["doc/index.html"])
	     
