Document: aldrin
Title: Debian aldrin Manual
Author: <insert document author here>
Abstract: This manual describes what aldrin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/aldrin/aldrin.sgml.gz

Format: postscript
Files: /usr/share/doc/aldrin/aldrin.ps.gz

Format: text
Files: /usr/share/doc/aldrin/aldrin.text.gz

Format: HTML
Index: /usr/share/doc/aldrin/html/index.html
Files: /usr/share/doc/aldrin/html/*.html

  
