#encoding: latin-1

# libzzub, Buzé, Aldrin
# Modular Sequencer
# Copyright (C) 2006 The Aldrin Development Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Import('env', 'posix', 'win32', 'install_lib', 'install', 'cl', 'vs_projects')

localenv = env.Clone()

localenv.Append(CPPPATH=[
	'include',
	'../../include',
])

localenv.Append(CCFLAGS=[
	'-DFLAC__NO_DLL',
	'-DVERSION="\\"1.1.2\\""',
])

files = [
	'bitbuffer.c',
	'bitmath.c',
	'cpu.c',
	'crc.c',
	'file_decoder.c',
	'file_encoder.c',
	'fixed.c',
	'float.c',
	'format.c',
	'lpc.c',
	'md5.c',
	'memory.c',
	'metadata_iterators.c',
	'metadata_object.c',
	'seekable_stream_decoder.c',
	'seekable_stream_encoder.c',
	'stream_decoder.c',
	'stream_encoder.c',
	'stream_encoder_framing.c',
]

localenv.StaticLibrary('${LIB_BUILD_PATH}/FLAC', files)
