Import('pluginenv', 'build_plugin')

localenv = pluginenv.Clone()

files = ["SID.cpp", "sidemu.cc", "envelope.cc", "extfilt.cc", "filter.cc", "pot.cc", 
         "voice.cc", "wave.cc", "wave6581__ST.cc", "wave6581_P_T.cc", "wave6581_PS_.cc",
         "wave6581_PST.cc", "wave8580__ST.cc", "wave8580_P_T.cc", "wave8580_PS_.cc", 
         "wave8580_PST.cc"]

build_plugin(localenv, "somono_sid", files)
