#encoding: latin-1

# Aldrin
# Modular Sequencer
# Copyright (C) 2006 The Aldrin Development Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Import('env', 'install', 'install_recursive', 'win32')
import glob

install('${ICONS_ALDRIN_PATH}/16x16', glob.glob('16x16/*.png'), 0644)
install('${ICONS_ALDRIN_PATH}/22x22', glob.glob('22x22/*.png'), 0644)
install('${ICONS_ALDRIN_PATH}/24x24', glob.glob('24x24/*.png'), 0644)
install('${ICONS_ALDRIN_PATH}/32x32', glob.glob('32x32/*.png'), 0644)
install('${ICONS_ALDRIN_PATH}/scalable', glob.glob('scalable/*.svg'), 0644)
if win32:
	install('${ICONS_ALDRIN_PATH}/aldrin', 'aldrin.ico', 0644)

