Import('env', 'posix', 'install_lib')

import glob

localenv = env.Clone()

files = ["Svf.cpp", "Adsr.cpp", "Lfo.cpp", "GrainEnv.cpp"]

lanternfish_static = localenv.StaticLibrary('${LIB_BUILD_PATH}/lanternfish', files)

