Import('env', 'posix', 'win32', 'install_lib', 'cl', 'vs_projects')
import glob

#######################################
#
# rubberband time stretching library
#
#######################################

localenv = env.Clone()

files = [
"src/RubberBandStretcher.cpp",
"src/ConstantAudioCurve.cpp",
"src/HighFrequencyAudioCurve.cpp",
"src/PercussiveAudioCurve.cpp",
"src/AudioCurve.cpp",
"src/Resampler.cpp",
"src/SpectralDifferenceAudioCurve.cpp",
"src/StretchCalculator.cpp",
"src/StretcherImpl.cpp",
"src/StretcherProcess.cpp",
"src/StretcherChannelData.cpp",
"src/FFT.cpp",
"src/Thread.cpp",
"src/sysutils.cpp"
]

localenv.Append(CPPPATH=[
	'rubberband',
])

#~ if cl:
	#~ localenv.Append(CCFLAGS=[
		#~ '-Dinline=__inline',
		#~ '-DFPM_INTEL', # this needs to be changed for other platforms
	#~ ])
#~ else:
	#~ localenv.Append(CCFLAGS=[
		#~ '-DHAVE_CONFIG_H',
		#~ '-DFPM_INTEL', # this needs to be changed for other platforms
	#~ ])

rubberband_static = localenv.StaticLibrary('${LIB_BUILD_PATH}/rubberband_static', files)

Export('rubberband_static')
