#encoding: latin-1

# libzzub, Buzé, Aldrin
# Modular Sequencer
# Copyright (C) 2006 The Aldrin Development Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Import('pluginenv', 'build_plugin')

build_plugin(pluginenv, 'Geonik_PrimiFun', [
	'BuzzMachines/PrimiFun.cpp',
])

build_plugin(pluginenv, 'Geonik_PluckedString', [
	'BuzzMachines/PluckedString.cpp',
])

# build_plugin(pluginenv, 'Geonik_Gapper', [
# 	'BuzzMachines/Gapper.cpp',
# ])

build_plugin(pluginenv, 'Geonik_DF_Filter', [
	'BuzzMachines/DfFilter.cpp',
],
	helpfiles=[
		#'Geonik_DF_Filter.html',
	]
)

# sndfile_pluginenv = pluginenv.Copy()
# sndfile_pluginenv.Append(LIBS=[
# 		'sndfile',
# 	])
# sndfile_pluginenv.Append(CCFLAGS=[
# 		'-DUSE_SNDFILE',
# 	])

# build_plugin(sndfile_pluginenv, 'Geonik_Omega1', [
# 	'BuzzMachines/Omega1.cpp',
# 	]
# )

