#encoding: latin-1

# libzzub, Buzé, Aldrin
# Modular Sequencer
# Copyright (C) 2006 The Aldrin Development Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Import('pluginenv', 'build_plugin')

build_plugin(pluginenv, 'matilde_tracker', files=[
		'BuzzInstrument.cpp',
		'BuzzSample.cpp',
		'Channel.cpp',
		'Envelope.cpp',
		'ExtResampler.cpp',
		'IInstrument.cpp',
		'ISample.cpp',
		'Track.cpp',
		'Tracker.cpp',
		'WavetableManager.cpp',
		'../SurfsDSPLib/SRF_2PFilter.cpp',
		'../SurfsDSPLib/SRF_Amp.cpp',
		'../SurfsDSPLib/SRF_AutoGain.cpp',
		'../SurfsDSPLib/SRF_DSP.cpp',
		'../SurfsDSPLib/SRF_Resampler.cpp',
	],
	helpfiles=[
		'index.html',
	])
